-- 사용자 고정비용 저장
ALTER TABLE users ADD COLUMN cost_rent INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN cost_labor INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN cost_material INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN cost_other INTEGER DEFAULT 0;
